### ISSUE TITLE
broken links in Getting Starter section

### ISSUE THREAD

**Issue by bigara** [gruntjs/grunt-docs#109]
Two broken links in getting starter section third paragraph. They lost the root directory: 
example >> links to http://sample-gruntfile/ in order to http://gruntjs.com/sample-gruntfile 
configure a task >>  links to http://configuring-tasks/ in order to http://gruntjs.com/configuring-tasks

**Comment by ericbinek** [comment]
Also on http://gruntjs.com/project-scaffolding#licenses.

init.addLicenseFiles links to a missing http://gruntjs.com/#initaddlicensefiles

**Comment by dkhamsing** [comment]
:+1:

**Comment by jhayotte** [comment]
Still the case!

**Comment by sindresorhus** [comment]
PR welcome.

**Comment by dkhamsing** [comment]
Looks like most issues are fixed

The only problem is the one reported by @ericbinek:

The markup is `Add custom licenses with [init.addLicenseFiles](#initaddlicensefiles).` which works on the md file 
- https://github.com/gruntjs/grunt-docs/blob/master/Project-Scaffolding.md 
- https://github.com/gruntjs/grunt-docs/blob/master/Project-Scaffolding.md#initaddlicensefiles

However on the website http://gruntjs.com/project-scaffolding that link becomes http://gruntjs.com/#initaddlicensefiles

We could update the link to point to http://gruntjs.com/project-scaffolding#init.addlicensefiles but then the md would be broken.. what do you think @sindresorhus
