### ISSUE TITLE
Missing grunt-file exit code was 99, documentation details exit code 2

### ISSUE THREAD

**Issue by paulhayes** [gruntjs/grunt-docs#121]
http://gruntjs.com/api/exit-codes says missing grunt file should return exit code 2. 

I ran the following and got exit code 99:
```
$ grunt --no-color --gruntfile ["web/app/themes/roots/Gruntfile.js"] build
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
$ echo $?
99
```

**Comment by boygreeny** [comment]
Did you resolve this issue? - same here

**Comment by JKAussieSkater** [comment]
The documentation is correct, and with my test, I'm getting the expected error code, 2.

Closing, as this is not a grunt-docs issue. Feel free to report the issue at [grunt](https://github.com/gruntjs/grunt/issues), however it might further help to include your Gruntfile.js configuration, and the following log information from your console:

    pwd
      /Users/USERNAME/Documents
    $node -v
      v0.0.0
    $grunt -version
      grunt-cli v0.0.0
      grunt v0.0.0

**Comment by paulhayes** [comment]
Apologies for writing it in the wrong place. Still happening for me, so I'll rereport. Might be an osX issue only.

**Comment by JKAussieSkater** [comment]
I'm on OSX, so it's not that, but it could be connected to your specific node & grunt version.

Good luck!

**Comment by cowboy** [comment]
@paulhayes is `grunt` installed locally? It looks like the error is complaining about not being able to find `grunt`, not not being able to find the Gruntfile.

**Comment by paulhayes** [comment]
Ah, yes. The ambiguity in the error message disguised this. Yes when grunt is installed, I get the correct error code.
