### ISSUE TITLE
Documentation unclear regarding array behaviour: `grunt.config.merge`

### ISSUE THREAD

**Issue by uglow** [gruntjs/grunt-docs#123]
When merging an array property:
```
src: {
  prop: ['a', 'b']
}

overlay: {
  prop: ['c']
}

grunt.config.set('myConfig', src);
grunt.config.merge({ src: overlay.prop });
```
This produces `{src: {prop: ['c', 'b']}}`. I was expecting it to produce `{src: {prop: ['c']}}`, as the `overlay.prop` property should replace the `src.prop` property, right?

**Comment by JKAussieSkater** [comment]
The `grunt.config.merge` function is working as it should, albeit, the documentation isn't sufficient enough to explain the behaviour.

Short story: Your code is generating the expected result `{ prop: ['c', 'b'] }`

Long story: When it comes to arrays, `grunt.config.merge` does a "merge and replace" based for each element in the array, ignoring undefined indexes. Here's a table, as an example:

Original Configuration | Merge Configuration | Output Configuration | Behaviour 
:---: | :---: | :---: | ---
`src` | `src` | `src` | Chosen property to merge contents with
`prop` | `prop` | `prop` | Chosen sub-property to merge contents with
`prop[0]` <br/>(= 'a') | `prop[0]` <br/>(= 'c') | `prop[0]` <br/>(= 'c') | Index 0 of the `prop` array gets replaced by merged configuration's value
`prop[1]` <br/>(= 'b') | `prop[1]` <br/>(= undefined) | `prop[1]` <br/>(= 'b') | Index 1 of the `prop` array does NOT get replaced by undefined indexes

To better achieve what you're trying to do, consider the following `Gruntfile.js` configuration.
I've emulated your code with task `issue-123`, and provided an alternative with task `solution-123`.

```js
/*jslint node: true*/
module.exports = function (grunt) {
  'use strict';
  grunt.initConfig({
    src: {
      prop: ['a', 'b']
    },
    overlay: {
      prop: ['c']
    }
  });
  grunt.registerTask('issue-123', 'Issue#123 original code', function () {
    grunt.config.get('src');      // { prop: ['a', 'b'] }
    grunt.config.get('overlay');  // { prop: ['c'] }
    grunt.config.set('myConfig', grunt.config.get('src'));
    grunt.config.get('myConfig'); // { prop: ['a', 'b'] }
    grunt.config.merge({ src: grunt.config.get('overlay') });
    grunt.config.get('src');      // { prop: ['c', 'b'] }
  });
  grunt.registerTask('solution-123', 'Issue#123 suggested solution', function () {
    grunt.config.get('src');      // { prop: ['a', 'b'] }
    grunt.config.get('overlay');  // { prop: ['c'] }
    grunt.config.set('myConfig', grunt.config.get('src'));
    grunt.config.get('myConfig'); // { prop: ['a', 'b'] }
    grunt.config.set('src.prop', grunt.config.get('overlay').prop);
    grunt.config.get('src');      // { prop: ['c'] }
  });
};
```

If you _really_ want to use the merge command to replace a single array property, try the following:

```js
grunt.registerTask('alternative-solution-123', 'Issue#123 suggested alternative solution', function () {
    grunt.config.get('src');      // { prop: ['a', 'b'] }
    grunt.config.get('overlay');  // { prop: ['c'] }
    grunt.config.set('myConfig', grunt.config.get('src'));
    grunt.config.get('myConfig'); // { prop: ['a', 'b'] }
    
    grunt.config.set('src.prop', undefined); // { prop: undefined }
    grunt.config.merge({ src: grunt.config.get('overlay') });
    grunt.config.get('src');      // { prop: ['c'] }
    
    // or if you wanted to merge ONLY the prop . . .
    grunt.config.set('src.prop', undefined); // { prop: undefined }
    grunt.config.merge({ src: { prop: grunt.config.get('overlay').prop } });
    grunt.config.get('src');      // { prop: ['c'] }
  });
```

**Comment by JKAussieSkater** [comment]
I'm going to re-purpose this ticket as a reminder to make the documentation more clear about this :wink:

**Comment by uglow** [comment]
Thanks for the clarification :)
