### ISSUE TITLE
Grunt Error

### ISSUE THREAD

**Issue by marathonrolando** [gruntjs/grunt-docs#130]
Hello. I am running Windows 7 Pro. I have followed this article for references:
http://www.ghosthorses.co.uk/production-diary/installing-grunt-on-os-x-and-windows-7/#grunt_win7
and 
http://gruntjs.com/getting-started

When I run npm uninstall -g grunt, it looks in the c:\users\appdata\roaming\npm\npm_modules folder where grunt is not installed but grunt-cli is. The grunt file is in grunt-cli\bin\ folder. I can copy the grunt file from bin to the npm_modules and the uninstall works. 

I will then run the next command npm install -g grunt-cli, I would delete the orginal grunt-cli folder and the command re-creates it. 

When I type grunt in the command prompt, it says it cant find grunt. I noticed it is looking again in the c:\users\appdata\roaming\npm\npm_modules folder. So I copy the grunt and grunt.cmd file to that folder and the command runs but now I get the error shown in the screenshot. I do have a .js file in a folder on my desktop. Am i suppose to edit the CMD file to point to that folder or do I have to specify the .js file?

![error](https://cloud.githubusercontent.com/assets/12299095/7519868/e178f056-f4b0-11e4-8542-7973eadc4907.JPG)

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
