### ISSUE TITLE
font weight 200 unreadable in chrome

### ISSUE THREAD

**Issue by DrCord** [gruntjs/grunt-docs#144]
the font-weight of the site documentation makes it utterly unreadable in chrome latest. I have perfect eyesight and I had to use the inspector to change the font-weight so I could use the site.

**Comment by JKAussieSkater** [comment]
The website reads fine for me, here's a screenshot of what I can see:
![grunt_chrome-v48_macosx-10.11](https://cloud.githubusercontent.com/assets/12983913/12970408/a0b5bcfc-d0e2-11e5-8381-401c1f3cbaca.jpg)

Would you be able to upload a screenshot, so we can understand which parts are unreadable? We'd really appreciate that!

**Comment by DrCord** [comment]
Attached is a screenshot from chrome latest on Windows 10, the main bodies of text are unreadable.
![grunt_site_screenshot](https://cloud.githubusercontent.com/assets/306243/12979072/c92ab948-d089-11e5-8f37-cfaa18629309.png)

**Comment by JKAussieSkater** [comment]
I see, the font 'Helvetica Neue' seems excessively thin (or light) in your browser.

Or perhaps it's displaying as the font intends in Windows, and simply my Mac enhances it to be more readable on my screen. There seemed to be heaps of controversy when Apple used Helvetica Neue as the default iOS system font, and many people were happy when they [changed to San Francisco](http://designforhackers.com/blog/apples-new-san-francisco-font/).

@vladikoff, @shama, @cowboy, Could we consider changing to a slightly thicker font than Helvetica Neue?

**Comment by dmethvin** [comment]
That's really strange, it looks fine on Windows 10 Chrome for me. Not sure why it looks so bad, there must be some setting or missing font issue?
![capture](https://cloud.githubusercontent.com/assets/157858/12998460/e126dd3c-d111-11e5-9495-673431b8b8e5.PNG)

**Comment by JKAussieSkater** [comment]
I suppose if the X-res x Y-res is not 1:1, it could cause issues like this as well.
@DrCord, Is your screen resolution setting optimal?

**Comment by DrCord** [comment]
Seems to work on all other sites, though I have noticed that sites using
Helvetica Neue tend to look bad sometimes.

**Comment by AurelioDeRosa** [comment]
I confirm the text doesn't look as per the screenshot. I'm on Windows 10 Pro and using Chrome 48.

**Comment by steveoh** [comment]
Closing as this seems to be a single users specific problem.

Please reopen if that is not the case. I am closing this from a windows 10 machine in chrome where the font looks fine.

**Comment by darkodelta** [comment]
Running Windows 10 Pro. Still looks super think like in DrCord screenshot. I am running on normal monitor without any scaling resolution.
