### ISSUE TITLE
Grunt is Bullshit!!

### ISSUE THREAD

**Issue by do4best** [gruntjs/grunt-docs#145]
Grunt task runner is really bullshit, that it is very hard for new learner, or there is no section built on your damn site to start with such from simple to complex.
There is no prerequisite and of course a hard nut to crack.
Searching a lot of materials and still unable to find the sckrach server.
You should developed a section for geecks like us or it seem a china wall for the hard learner.

**Comment by vladikoff** [comment]
Thanks for the feedback, Happy new year!
