### ISSUE TITLE
Reminder: update the date to 2016 at the bottom of the wiki

### ISSUE THREAD

**Issue by pye2k** [gruntjs/grunt-docs#147]
http://gruntjs.com/api/grunt.template

Happy New Year!

**Comment by vladikoff** [comment]
@shama did you have a script for this?

**Comment by pye2k** [comment]
Alternative is that I submit a pull request to fix strings... LMK.

**Comment by shama** [comment]
Yep! I'll fire it up.

**Comment by shama** [comment]
Done.

**Comment by shama** [comment]
https://github.com/gruntjs/grunt-docs/commit/5b609408058f03e3df922c7c8079a50c30b8972c

**Comment by vladikoff** [comment]
![](https://media.giphy.com/media/Bc5W3l2V7lPmU/giphy.gif)
