### ISSUE TITLE
grunt.template.today() example out of date

### ISSUE THREAD

**Issue by mattce** [gruntjs/grunt-docs#151]
A reminder to update the grunt.template.today() example to use the current year.
Currently it it says:
`grunt.template.today('yyyy') // '2015'`
but should be
`grunt.template.today('yyyy') // '2016'`

See here: http://gruntjs.com/api/grunt.template

**Comment by JKAussieSkater** [comment]
Hi! Thanks for the reminder!
Actually, this has already been addressed in the [grunt-docs/grunt.template.md](https://github.com/gruntjs/grunt-docs/blob/master/grunt.template.md) file. [See this commit](https://github.com/gruntjs/grunt-docs/commit/5b609408058f03e3df922c7c8079a50c30b8972c#diff-830d823b4996475f2c9456d7cb385b68).

Unfortunately, the GruntJS website is out-of-sync with grunt-docs at the moment . . . Long story short, I think we're in the process of changing server hosts (have I got that right? @vladikoff).

@mattce, I was wondering if we should open a new issue here, and explain that the website is out-of-sync with Git? That way at least the issue can be tracked.
