### ISSUE TITLE
Grunt website is out-of-sync with Git (gruntjs/grunt-docs)

### ISSUE THREAD

**Issue by JKAussieSkater** [gruntjs/grunt-docs#153]
Unfortunately, the GruntJS website is out-of-sync with grunt-docs at the moment.

Long story short, I think we're in the process of changing server hosts for the website (@vladikoff, have I got that right?).

Some users are starting to notice (#151, #152), so I'm opening this ticket to track the issue.

**Comment by vladikoff** [comment]
> I think we're in the process of changing server hosts for the website (@vladikoff, have I got that right?).

Yeap exactly, it is almost ready!

**Comment by JKAussieSkater** [comment]
Accidentally closed issue.

Progress update, for anybody reading this: We've set up the website with our new hosts, it won't be long before the changes go live!

**Comment by JKAussieSkater** [comment]
WooHoo!!! [gruntjs.com/releases/tag/v1.0.5](https://github.com/gruntjs/gruntjs.com/releases/tag/v1.0.5)!

Grunt-Docs are back in sync! :+1:
