### ISSUE TITLE
Update getting started for 1.0.0

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/grunt-docs#155]
In getting started we say 

> Grunt 0.4.x requires stable Node.js versions >= 0.8.0. Odd version numbers of Node.js are considered unstable development versions.

We should drop node 0.8 for 1.0

cc @shama @JKAussieSkater

**Comment by shama** [comment]
We should just list the versions of Node.js Grunt is compatible with instead.

**Comment by JKAussieSkater** [comment]
Both ideas perhaps?

Drop v0.8, and change the sentence to a list of Node versions:

> Grunt is compatible with the following versions of Node:
> * v1.0.0
> * v1.2.0
> * . . .

**Comment by shama** [comment]
Grunt 1.x.x is compatible with the following versions of Node.js:
* v0.10
* v0.12
* io.js v3.3
* v4.x
* v5.x

**Comment by XhmikosR** [comment]
Shouldn't we specify a minimum npm version, mostly for node.js 0.10? Does everything work with the default npm that ships with node.js 0.10?

**Comment by shama** [comment]
@XhmikosR That's a good idea. I'd say `npm >= 2.0.0`. The good part is npm is a dev dep for users, so asking to upgrade is easier (although a lot people have been resistant to 3.0.0).

**Comment by XhmikosR** [comment]
Won't the property be applied for normal users too who just do `npm i`? the same as the node property does.

**Comment by shama** [comment]
@XhmikosR Sorry I dont follow.

**Comment by XhmikosR** [comment]
@shama:
>The good part is npm is a dev dep for users.

Why do you think it's a dev dep? Every user who does `npm i` is using npm... So if things don't work with npm 1.x, the package won't be possible to install.

Correct me if I'm wrong.

**Comment by shama** [comment]
@XhmikosR What I mean by it's a dev dep is it's a dependency that should be specifically used for development. So if a package cannot install because a user is using `npm@1.x`, we can simply tell them to `npm i npm -g`.

As opposed to the version of Node.js which may not be as easy for a user to upgrade. It affects code beyond just while in development. Hopefully that makes sense?
