### ISSUE TITLE
Add migration guide for 0.4 to 1.0.0

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/grunt-docs#164]
Basically a copy of http://gruntjs.com/upgrading-from-0.3-to-0.4 but with all the new stuff.

I think it is mostly: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies

and: 
 "Be advised Grunt 1.0.0 will no longer support Node.js v0.8."

and:

a bit of from: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#api-changes

and: 

maybe suggest that it is now possible to avoid installing grunt-cli: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#npm-scripts

cc @JKAussieSkater

**Comment by coliff** [comment]
I guess this Issue can be closed now.
REF: http://gruntjs.com/upgrading-from-0.4-to-1.0

**Comment by vladikoff** [comment]
Yeap thank you!
