### ISSUE TITLE
Happy Valentines Day!

### ISSUE THREAD

**Issue by JKAussieSkater** [gruntjs/grunt-docs#167]
# Happy Valentines Day Grunt!
![grunt heart](https://cloud.githubusercontent.com/assets/12983913/13027398/87d2b5e8-d2a2-11e5-8c31-be74fcd3c53d.png)

#### You'll be forever loved, my faithful JavaScript task runner.

**Comment by dmethvin** [comment]
See GitHub, *this* is why we need a Like button.

**Comment by JKAussieSkater** [comment]
:+1:
