### ISSUE TITLE
New to open source guide

### ISSUE THREAD

**Issue by shama** [gruntjs/grunt-docs#168]
@vladikoff @JKAussieSkater What do you think about a guide aimed towards those new to open source to help contribute to Grunt?

We can create a label across the repos that signifies an issue good for beginners (not sure of the exact label name. I've seen `first-timers-only`, `beginners`, etc but haven't really liked any of those label names).

I can help get the guide started. Let me know what you all think.

**Comment by JKAussieSkater** [comment]
Great idea!

* How detailed?
  * How to use GitHub?

**Comment by vladikoff** [comment]
Should just improve this page: http://gruntjs.com/contributing

**Comment by vladikoff** [comment]
> How to use GitHub?

There are plenty of guides that we can just link to

**Comment by shama** [comment]
Ah good call @vladikoff, I'll just work on updates to that page. Thanks!
