### ISSUE TITLE
Add an example for Grunt specific options vs task options

### ISSUE THREAD

**Issue by shama** [gruntjs/grunt-docs#169]
I've noticed a few issues with people getting confused on what is a task option vs Grunt option. Such as `filter` and `nonull`: https://github.com/gruntjs/grunt-contrib-concat/issues/93

On this page: http://gruntjs.com/configuring-tasks#files it would be good to add an example and a little bit of text about it to link people to.

**Comment by AurelioDeRosa** [comment]
I can give this issue a try if everyone is fine with that.

**Comment by JKAussieSkater** [comment]
@AurelioDeRosa, :+1:

**Comment by shama** [comment]
Nice work! :D
