### ISSUE TITLE
grunt.template.today - year reminder

### ISSUE THREAD

**Issue by bbolgradov** [gruntjs/grunt-docs#195]
> (somebody remind me to update this date every year so the docs appear current)

Hey, as you asked, I'm reminding you to update the year in the grunt.template documentation.

Not making a pull request, so you can have the pleasure! ;)

**Comment by franciscop** [comment]
It broke some tests for a totally unrelated issue few packages down the chain:

- https://github.com/gruntjs/grunt-contrib-pug/pull/173

Note: to be fair, that's the doc with a notice which should have given a clue to the maintainer of  `grunt-contrib-pug` as not to use it for testing.

**Comment by vladikoff** [comment]
https://github.com/gruntjs/grunt-docs/commit/28b81d8356f11efc4aa22a4b2d2323b20028f5f4
