### ISSUE TITLE
Change current year in the last example of templates

### ISSUE THREAD

**Issue by mehocode** [gruntjs/grunt-docs#209]
Found this while was reading the documentation:

In this example, today's date is formatted as a 4-digit year.

`grunt.template.today('yyyy') // '2017'`

(somebody remind me to update this date every year so the docs appear current)

---
Direct link to the page: https://gruntjs.com/api/grunt.template

**Comment by Joel-Kornbluh** [comment]
🤣 That's how they communicated in the stone age...

**Comment by EarthenForger** [comment]
Friendly reminder to update this for 2020 :)
