### ISSUE TITLE
Every time, it report this error,but I truely use npm install grunt-cli -g!

### ISSUE THREAD

**Issue by pumpkinpies** [gruntjs/grunt-docs#210]
ubuntu@VM-162-175-ubuntu:~$ grunt
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started

Can any body help me , I am going to be crazy..QAQ

**Comment by vladikoff** [comment]
'If you're seeing this message, grunt hasn't been installed locally to
your project'

**Comment by steveoh** [comment]
so to answer your question you still need to `npm install grunt` even though you have `npm install grunt-cli -g`
