### ISSUE TITLE
Documentation should indicate "not for Windows" if that is true

### ISSUE THREAD

**Issue by David263** [gruntjs/grunt-docs#213]
The home page and Getting Started should make it clear that this is a Linux tool, and not useful under Windows (if that is true). I am a Windows user and frequently find that the latest technology is specifically or mainly for use on Linux systems. Not that I have any blame to offer, since Windows is oriented toward different development patterns. Windows doesn't come with npm, node, rails, perl, ruby, or other Linux-style tools. It doesn't even have a standard and accepted Linux emulator.

**Comment by vladikoff** [comment]
We run CI tests on Windows and they pasd
