### ISSUE TITLE
Fatal error: Unable to find local grunt.

### ISSUE THREAD

**Issue by johnjbarton** [gruntjs/grunt-docs#38]
Pretty much my user experience with grunt:

```
>grunt
```

```
grunt-cli: The grunt command line interface. (v0.1.11)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
```

---

Ok, then:

```
>sudo npm install -g grunt-cli
```

```
npm http GET https://registry.npmjs.org/grunt-cli
npm http 304 https://registry.npmjs.org/grunt-cli
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/findup-sync
npm http GET https://registry.npmjs.org/resolve
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/findup-sync
npm http 304 https://registry.npmjs.org/resolve
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt-cli/bin/grunt
grunt-cli@0.1.11 /usr/local/lib/node_modules/grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.4)
└── findup-sync@0.1.2 (lodash@1.0.1, glob@3.1.21)
```

```
> grunt
```

Same as above

**Comment by stephaneeybert** [comment]
On my previous Linux box I succeeded in using grunt from a project directory, without having a node_modules directory in it. But I cannot replicate this on a new Linux machine. The .profile file contains in both cases: export NODE_HOME=/home/stephane/programs/install; PATH=$PATH:$NODE_HOME/bin; export NODE_PATH=/home/stephane/programs/install/lib/node_modules

**Comment by anakinjay** [comment]
+1 for this.  I'm new to grunt and just spent hours trying to figure this error message out.   Even something like: 

"Unable to find local grunt. Have you installed grunt locally with 'npm install' ?"  

would be much much better.

**Comment by westerdaled** [comment]
I am also  finding getting Grunt to work very torturous.  http://stackoverflow.com/questions/36663055/grunt-serve-warning-task-serve-not-found-use-force-to-continue-revisited?noredirect=1#comment60934232_36663055 .  I am now stuck  

> Warning: Task "serve" not found. Use --force to continue

**Comment by AurelioDeRosa** [comment]
The problem might come from the fact that you're using a newer version of webapp-generator. This boilerplate has moved from Grunt to Gulp, that's why it isn't working. Check if you find a `gulpfile.js` in your folder.

**Comment by larka06** [comment]
I fine the grunt starter page **useless**...it **assumes** to many things are known...I was not able to find the info I needed to understand being new to this subject

**Comment by belalmr** [comment]
# ## ##jjjj

**Comment by mannyr7** [comment]
First off, I am new to this. It started with wanting to install and run, pyjs on my Windows machine. No groans please. So, down the rabbit hole we go with installing dependencies, composer, npm, jquery, node js, eslint, ajv, and finally stuck here at grunt. As stated above, WAY too much is assumed on the Getting-Started page. I just want to run Hello.py after the bootstrap install. Being new, I have no clue what SHOULD go in a gruntfile, what resources commonly need referencing or where to properly put it for this and other projects. By a global install, I assumed the same gruntfile would be found and used for every project, but not so, or I am doing it completely wrong.

**Comment by Eddcapone** [comment]
2020 and they still did not improved their documentation...

**Comment by Abhishek2kr** [comment]
After running all right commands it fails then try those commands after running this
```npm config set registry https://registry.npmjs.com/```

[https://stackoverflow.com/a/75183131/10373693]( ref )
