### ISSUE TITLE
Create a page that explains why installing Grunt globally is bad

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/grunt-docs#43]
Ref: https://github.com/gruntjs/grunt-cli/issues/10#issuecomment-34008518

**Comment by JKAussieSkater** [comment]
Long story short:
* Install `grunt-cli` globally
* Install `grunt` locally to each project

For inspiration: [npm 1.0: Global vs Local installation](http://nodejs.org/en/blog/npm/npm-1-0-global-vs-local-installation/)

I _might_ make a draft of this, however I feel I'm not an authority on the matter (I'd submit a draft and some more experienced folk could edit it).
